[package]
name = "tray-bright"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
eframe = { version = "0.30", default-features = false, features = ["glow", "default_fonts"] }
env_logger = "0.11.8"
image = "0.25.5"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
tray-icon = { version = "0.21.3", features = ["serde"] }
wmi = "0.18.0"

[dependencies.windows]
version = ">=0.59, <=0.62"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Devices_Display",
  "Win32_System_Registry",
]
